name: klix-flows
prefect-version: ">=3.0.0"

pull:
- prefect.deployments.steps.git_clone:
    repository: "https://github.com/KlixMediaAds/klix-flows.git"
    branch: "main"

deployments:
- name: send-queue
  entrypoint: "flows/send_queue.py:send_queue"
  version: "{{ git_sha }}"
  work_pool:
    name: klix-managed
    job_variables: {}
  tags: ["send"]
  parameters:
    batch_size: 25
    target_per_hour: 30
    jitter_extra_s: 20
    business_hours: "09:00-17:00"
    timezone: "America/Toronto"
    friendlies_first: true
    dry_run: false
  schedules:
  - interval: 600.0   # every 10 minutes
